remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: hyhy-masa
      url-base: https://github.com/hyhy-masa
    - name: caksoylar
      url-base: https://github.com/caksoylar  
  projects:
    - name: zmk
      remote: zmkfirmware  # <-- hyhy-masa から zmkfirmware に変更
      revision: main       # <-- 09ee8b42 から main に変更
      import: app/west.yml
